version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:8080"
    environment:
      - PORT=8080
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - DB_NAME=oblix
    volumes:
      # Mount environment file
      - ./.env:/app/.env:ro
      # Mount uploads directory for file persistence
      - ./uploads:/app/uploads
      # Mount logs directory for log persistence
      - ./logs:/app/logs
      # Mount node_modules for development
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 